### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by sheriffmarley** [Dionera/laravel-beanstalkd-admin-ui#19]
Since Laravel upgraded pheanstalk to version 4 in laravel 5.8, the package isn't working with it anymore. 

Will there be an update?

**Comment by ksassnowski** [comment]
Thanks for bringing this to my attention. I'll try and publish an update tonight.

**Comment by ksassnowski** [comment]
Sorry for the delay. This should be fixed in the [2.0.0](https://github.com/Dionera/laravel-beanstalkd-admin-ui/releases/tag/2.0.0) release.
