### ISSUE TITLE
Laravel 6.* Support

### ISSUE THREAD

**Issue by TheFrankman** [Dionera/laravel-beanstalkd-admin-ui#22]
Hello There, 

Any chance of laravel 6 support in the near future ?

Thanks

**Comment by TheFrankman** [comment]
FYI - I've modified composer on my fork to allow `^6.0` and everything still works.

**Comment by ksassnowski** [comment]
I just published a new release `2.0.1` that adds support for Laravel 6. Thanks for bringing this to my attention :+1:
