### ISSUE TITLE
Laravel 5.1 support

### ISSUE THREAD

**Issue by kusut** [Dionera/laravel-beanstalkd-admin-ui#3]
Hey. Thank you for the project!

Right now, despite having a default middleware in `resource/config`, the project has `web` middleware hardcoded in its routes definition (`https://github.com/Dionera/laravel-beanstalkd-admin-ui/blob/master/src/routes.php#L3`). AFAIK this is the only blockage to have this project embedded in a laravel 5.1 app.  

Is it possible to have it removed in the routes definition?

**Comment by ksassnowski** [comment]
I think the idea was, that I wanted the UI routes to always have the `web` middleware group, regardless of what is configured in the config. But I will look into it tonight. Can you tell me what exactly about that line is causing an incompatibility with Laravel 5.1?

**Comment by kusut** [comment]
Laravel 5.2 introduced [middleware groups](https://mattstauffer.co/blog/middleware-groups-in-laravel-5-2), and `web` is one of the built-ins. So having that middleware in routes will break laravel 5.1 projects (`Class web does not exist`).

Possible solutions:
- Do not define any middleware in beanstalkdui routes
- Use `auth` in beanstalkdui routes

CMIIW, either way, it will be merged with default config (resources/config/beanstalkdui), that has both `web` and `auth`, right?

Thanks

**Comment by ksassnowski** [comment]
Just letting you know that I haven't forgotten about this. I just haven't found the time to look into it yet!

**Comment by ksassnowski** [comment]
This is resolved with the `0.3.4` release. Please refer to the updated readme for Laravel 5.1 support. https://github.com/Dionera/laravel-beanstalkd-admin-ui#laravel-51
