### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by tybricks** [Dionera/laravel-beanstalkd-admin-ui#35]
Hello thx for you amazing work !

Could you allow php8.0 compatibility for Beanstalkd-admin-ui ?

composer.json
```
"require": {
    "php": "^7.4|^8.0",
    .....
},
```

Regards

**Comment by ksassnowski** [comment]
Fixed in [4.0.0](https://github.com/Dionera/laravel-beanstalkd-admin-ui/releases/tag/4.0.0)
