### ISSUE TITLE
Resource files do not load !

### ISSUE THREAD

**Issue by andrbee** [Dionera/laravel-beanstalkd-admin-ui#38]
![Screenshot from 2022-05-10 18-32-26](https://user-images.githubusercontent.com/8384894/167666614-484fe718-8d40-41f4-96c5-6c1e467cbd10.png)

**Comment by andrbee** [comment]
added vendor/dionera/laravel-beanstalkd-ui/src/Resources/assets/* folders to public/vendor/beanstalkdui

**Comment by ksassnowski** [comment]
Did you run:

```
php artisan vendor:publish --provider="Dionera\BeanstalkdUI\BeanstalkdUIServiceProvider" --tag="public"
```

You shouldn't have to manually copy over anything.
